name: Run Unit Tests and Lint Files
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: |
          npm ci
          npm run build
          npm run test
          npm run lint
          npm run start & wait-on http://localhost:3000
          npm run e2e
